#!/usr/bin/env python3
import sys, base64, re, os

PEM_CERT = re.compile(rb"-----BEGIN CERTIFICATE-----(.*?)-----END CERTIFICATE-----", re.S)

def asn1_parse_one(buf, off):
    tag = buf[off]
    n = buf[off + 1]
    if n & 0x80:
        k = n & 0x7f
        L = 0
        for i in range(k):
            L = (L << 8) | buf[off + 2 + i]
        hdr = 2 + k
    else:
        L = n
        hdr = 2
    return tag, off + hdr, L

def find_spki_and_subject(der):
    """Return (spki_off, spki_len, subj_off, subj_len, nb, na) by walking TBS."""
    _, p, _ = asn1_parse_one(der, 0)              # Cert SEQUENCE
    _, t, tbs_len = asn1_parse_one(der, p)        # TBSCertificate SEQUENCE
    cur = t
    end = t + tbs_len

    tag, val_off, val_len = asn1_parse_one(der, cur)
    if tag == 0xa0:
        cur = val_off + val_len
    else:
        pass

    tag, val_off, val_len = asn1_parse_one(der, cur)
    cur = val_off + val_len

    tag, val_off, val_len = asn1_parse_one(der, cur)
    cur = val_off + val_len

    tag, val_off, val_len = asn1_parse_one(der, cur)
    issuer_off = val_off - (2 if val_len < 128 else (3 if val_len < 256 else 4))
    cur = val_off + val_len

    validity_tag, validity_val, validity_len = asn1_parse_one(der, cur)
    nb = parse_time(der, validity_val)
    cur_v = validity_val
    while cur_v < validity_val + validity_len:
        ttag, tval, tlen = asn1_parse_one(der, cur_v)
        cur_v = tval + tlen
    na_off = validity_val
    nb_tag, nb_val, nb_len = asn1_parse_one(der, na_off)
    nb = parse_time(der[nb_val:nb_val+nb_len], 0)
    na_tag, na_val, na_len = asn1_parse_one(der, nb_val + nb_len)
    na = parse_time(der[na_val:na_val+na_len], 0)
    cur = validity_val + validity_len

    subj_tag, subj_val, subj_len = asn1_parse_one(der, cur)
    hdr_size = subj_val - cur
    subj_off = cur
    subj_total = hdr_size + subj_len
    cur = subj_val + subj_len

    spki_tag, spki_val, spki_len = asn1_parse_one(der, cur)
    spki_hdr = spki_val - cur
    spki_off = cur
    spki_total = spki_hdr + spki_len

    return spki_off, spki_total, subj_off, subj_total, nb, na

def parse_time(buf, off):
    if not buf: return 0
    s = buf.decode("ascii", errors="ignore")
    if len(s) < 11: return 0
    if len(s) >= 13 and s[-1] == 'Z' and s[0:4].isdigit():
        yr = int(s[0:4]); o = 4
    else:
        yy = int(s[0:2]); yr = 2000 + yy if yy < 50 else 1900 + yy; o = 2
    mo = int(s[o:o+2]); d = int(s[o+2:o+4])
    h = int(s[o+4:o+6]); m = int(s[o+6:o+8]); se = int(s[o+8:o+10])
    import calendar
    return int(calendar.timegm((yr, mo, d, h, m, se, 0, 0, 0)))

def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: gen_ca_bundle.py <bundle.pem> <out.inc>\n")
        sys.exit(2)
    pem = open(sys.argv[1], "rb").read()
    entries = []
    for m in PEM_CERT.finditer(pem):
        b64 = re.sub(rb"\s+", b"", m.group(1))
        der = base64.b64decode(b64)
        try:
            spki_off, spki_len, subj_off, subj_len, nb, na = find_spki_and_subject(der)
        except Exception:
            continue
        entries.append((der, spki_off, spki_len, subj_off, subj_len, nb, na))

    out = open(sys.argv[2], "w")
    out.write("/* Auto-generated by tools/gen_ca_bundle.py. DO NOT EDIT. */\n")
    out.write(f"/* {len(entries)} CAs */\n\n")
    for i, (der, _, _, _, _, _, _) in enumerate(entries):
        out.write(f"static const uint8_t ca_der_{i}[] = {{")
        for j, b in enumerate(der):
            if j % 16 == 0: out.write("\n    ")
            out.write(f"0x{b:02x}, ")
        out.write("\n};\n\n")

    out.write("static const speer_ca_entry_t generated_ca_entries[] = {\n")
    for i, (der, sp_o, sp_l, su_o, su_l, nb, na) in enumerate(entries):
        out.write(f"    {{ ca_der_{i}, sizeof(ca_der_{i}), {sp_o}, {sp_l}, {su_o}, {su_l}, {nb}, {na} }},\n")
    out.write("};\n\n")
    out.write("static const speer_ca_store_t generated_ca_store = {\n")
    out.write("    generated_ca_entries,\n")
    out.write(f"    {len(entries)}\n")
    out.write("};\n")
    out.close()

if __name__ == "__main__":
    main()
